name: Run an Experiment
on:
  push:
    branches-ignore:
      - main
permissions:
  contents: write
  id-token: write
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    environment: cloud
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          role-duration-seconds: 43200
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml runner launch --single \
            --cloud-spot \
            --labels=cml \
            --cloud=aws \
            --cloud-region=us-west-2 \
            --cloud-hdd-size=100 \
            --cloud-type=t3.medium
  runner-job:
    needs: deploy-runner
    runs-on: [ self-hosted, cml ]
    environment: cloud
    container:
      image: iterativeai/cml:0-dvc2-base1-gpu
      options: --gpus all
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          role-duration-seconds: 43200
      - name: training
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          STUDIO_TOKEN: ${{ secrets.STUDIO_TOKEN }}
          STUDIO_REPO_URL: ${{ secrets.STUDIO_REPO_URL }}
          DVCLIVE_LOGLEVEL: DEBUG
        run: |
          pip install -r requirements.txt
          pip install "dvc[s3]"
          dvc doctor
          git fetch --prune
          echo "reproduce" >> report.md
          cml comment update --publish report.md
